src/Distance-Analyzer/Models/Node.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Distance_Analyzer.Models
{
    public class Node
    {
        public string id { get; set; } = Guid.NewGuid().ToString();

        /// <summary>
        /// A generic description, i.e. name, for the node
        /// </summary>
        public String Description { get; set; }

        /// <summary>
        /// The node's raw address entry
        /// </summary>
        public String Raw { get; set; }

        /// <summary>
        /// The node's scrubbed address
        /// </summary>
        public String Address { get; set; }

        public Double Latitude { get; set; }

        public Double Longitude { get; set; }

        /// <summary>
        /// A list of tags applied to this node for identification
        /// </summary>
        [NotMapped]
        public String[] Tags { get; set; } = new String[] { };

        public String TagsList
        {
            get { return JsonConvert.SerializeObject(Tags); }
            set { Tags = JsonConvert.DeserializeObject<String[]>(value); }
        }

        /// <summary>
        /// True if the node should be considered a super node, where all other nodes are calculated in relation to
        /// </summary>
        [Display(Name = "Is a Super Node?")]
        public Boolean Is_Super_Node { get; set; }

        /// <summary>
        /// A list of distance mapping between this node and the super nodes
        /// </summary>
        [NotMapped]
        public ICollection<Distance> Mappings { get; set; } = new List<Distance>();

        public String MappingsList
        {
            get { return JsonConvert.SerializeObject(Mappings); }
            set { Mappings = JsonConvert.DeserializeObject<List<Distance>>(value); }
        }
    }

    public sealed class Distance
    {
        /// <summary>
        /// Which node this mapped distance is in relation to
        /// </summary>
        public String To { get; set; }

        /// <summary>
        /// The calculated driving time under usual conditions to this node
        /// </summary
        [Display(Name = "Drive Time")]
        public TimeSpan Driving_Time { get; set; }

        /// <summary>
        /// The driving distance in miles to this node
        /// </summary>
        [Display(Name = "Distance (Meters)")]
        public Decimal Distance_Meters { get; set; }
    }
}

src/Distance-Analyzer/Controllers/HomeController.cs
using Distance_Analyzer.Models;
using Distance_Analyzer.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Distance_Analyzer.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private Database Db { get; }

        private IMapsService Maps { get; }

        public HomeController(Database db, IMapsService maps)
        {
            Db = db;
            Maps = maps;
        }

        public async Task<IActionResult> Index(IEnumerable<String> tags, String supernode)
        {
            ViewBag.tags = tags;
            ViewBag.supernode = supernode;

            ViewBag.SuperNodes = await Db.Nodes.Where(node => String.IsNullOrWhiteSpace(supernode) || node.id == supernode).Where(node => node.Is_Super_Node).ToListAsync();

            var nodes = await Db.Nodes.Where(node => !node.Is_Super_Node).ToListAsync();

            if (tags.Any())
            {
                nodes = nodes.Where(node => tags.Intersect(node.Tags).Any()).ToList();
            }

            // Returns a list of nodes

            return View(nodes);
        }

        [Route("~/Nodes/{id}")]
        public async Task<IActionResult> Node(String id)
        {
            // Return details of a single node

            var node = await Db.Nodes.FindAsync(id);

            if (node.Is_Super_Node)
            {
                // If it's a super node, go grab the details for other nodes mapped to it

                var mappings = from sub in Db.Nodes
                               from map in sub.Mappings
                               where map.To == node.id
                               select new Distance
                               {
                                   To = sub.id,
                                   Distance_Meters = map.Distance_Meters,
                                   Driving_Time = map.Driving_Time
                               };

                node.Mappings = mappings.ToList();
            }

            // Provide handler to 'Process' node

            return View(node);
        }

        [Route("~/Nodes/Scrub")]
        public IActionResult Scrub()
        {
            // Provide a raw address input form

            return View(Enumerable.Empty<MapsService.Result>());
        }

        [Route("~/Nodes/Scrub"), HttpPost]
        public async Task<IActionResult> Scrub(String raw_address)
        {
            // Scrub the incoming raw address, provide selection if multiple or create new node

            var results = await Maps.Scrub(raw_address);

            var count = results.Count();

            if (count == 1)
            {
                var first = results.First();

                return View(nameof(New), new Node
                {
                    Raw = raw_address,
                    Address = first.Address,
                    Latitude = first.Latitude,
                    Longitude = first.Longitude
                });
            }

            // 0 or many matches

            return View(results);
        }

        [Route("~/Nodes/New")]
        public IActionResult New()
        {
            // New node form

            return View(new Node { });
        }

        [Route("~/Nodes/{id}/Edit")]
        public async Task<IActionResult> Edit(string id)
        {
            return View(nameof(New), await Db.Nodes.FindAsync(id));
        }

        [Route("~/Nodes/New"), HttpPost]
        public async Task<IActionResult> New(Node node)
        {
            if (await Db.Nodes.AnyAsync(_ => _.id == node.id))
            {
                Db.Nodes.Update(node);
            }
            else
            {
                // Store a new node to the list

                await Db.Nodes.AddAsync(node);
            }

            await Db.SaveChangesAsync();

            return RedirectToAction(nameof(Node), new { node.id });
        }

        [Route("~/Nodes/{id}/Delete"), HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var node = await Db.Nodes.FindAsync(id);

            Db.Nodes.Remove(node);

            await Db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Route("~/Nodes/{id}/Process"), HttpPost]
        public async Task<IActionResult> Process(String id)
        {
            // Process the given node id with respect to the various super nodes, storing results

            var node = await Db.Nodes.FindAsync(id);

            var superNodes = await Db.Nodes.Where(_ => _.Is_Super_Node).ToListAsync();

            await Maps.Process(node, superNodes);

            await Db.SaveChangesAsync();

            return RedirectToAction(nameof(Node), new { id });
        }

        [HttpPost]
        public async Task<IActionResult> Process_All(int take = 10)
        {
            // Process all of the nodes

            var super_nodes = await Db.Nodes.Where(_ => _.Is_Super_Node).ToListAsync();

            var to_process = await Db.Nodes.Where(_ => !_.Is_Super_Node).Where(_ => !_.Mappings.Any()).Take(take).ToListAsync();

            foreach (var node in to_process)
            {
                await Maps.Process(node, super_nodes);
            }

            await Db.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Dump()
        {
            var nodes = await Db.Nodes.ToListAsync();

            var supernodes = nodes.Where(_ => _.Is_Super_Node);

            // Blah, hardcoding?

            var model = from node in nodes
                        where node.Is_Super_Node == false
                        let assigned = supernodes.Where(_ => node.Tags.Contains(_.Description)).SingleOrDefault()
                        let current = node.Mappings.Where(_ => _.To == assigned?.id).SingleOrDefault()
                        let pinellas = node.Mappings.Where(_ => _.To == "5c2503cb-3f0f-4ecb-a1a5-5b0788870307").SingleOrDefault()
                        let lakeland = node.Mappings.Where(_ => _.To == "40aa4091-886b-45ff-990a-10a22c017747").SingleOrDefault()
                        let brooksville = node.Mappings.Where(_ => _.To == "56b3690b-e16f-4030-af72-1a28e029de7a").SingleOrDefault()
                        select new
                        {
                            node.Description,
                            node.Tags,
                            Unit = assigned?.Description,
                            Current = current?.Driving_Time,
                            DeltaPinellas = pinellas?.Driving_Time - current?.Driving_Time,
                            DeltaLakeland = lakeland?.Driving_Time - current?.Driving_Time,
                            DeltaBrooksville = brooksville?.Driving_Time - current?.Driving_Time,
                        };

            return Json(model);
        }

        [AllowAnonymous]
        public IActionResult Login(String returnUrl = "/")
        {
            return new ChallengeResult("Auth0", new AuthenticationProperties { RedirectUri = returnUrl });
        }

        public async Task Logout()
        {
            await HttpContext.Authentication.SignOutAsync("Auth0", new AuthenticationProperties
            {
                RedirectUri = Url.Action(nameof(Index))
            });

            await HttpContext.Authentication.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        public IActionResult Backup()
        {
            var data = System.IO.File.ReadAllBytes("Data.db");

            var mimeType = "application/octet-stream";

            return File(data, mimeType);
        }

        public IActionResult Error()
        {
            return View();
        }
    }

    public class MapViewComponent : ViewComponent
    {
        private readonly GoogleMapsSettings Settings;

        private readonly Database Db;

        public MapViewComponent(GoogleMapsSettings settings, Database db)
        {
            this.Settings = settings;
            this.Db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id)
        {
            ViewBag.APIKey = Settings.Key;

            // TODO What do we need to generate a map?

            return View();
        }
    }

    public class NodeViewComponent : ViewComponent
    {
        private readonly Database db;

        public NodeViewComponent(Database db)
        {
            this.db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(string id)
        {
            return View(await db.Nodes.FindAsync(id));
        }
    }
}

src/Distance-Analyzer/Views/Home/Index.cshtml
@using System.Linq;
@model IEnumerable<Distance_Analyzer.Models.Node>

<div class="btn-group">
    <div class="btn btn-default">@Html.ActionLink("Add Node", "Scrub")</div>
</div>

<table class="table">

    <thead>
        <tr>
            <th>@Html.DisplayNameFor(_ => _.FirstOrDefault().Tags)</th>
            <th>@Html.DisplayNameFor(_ => _.FirstOrDefault().Description)</th>
            <th></th>
            @foreach (var supernode in ViewBag.SuperNodes)
            {
                <th>@Html.ActionLink($"{supernode.Description}", "Index", "Home", new { supernode = supernode.id, ViewBag.tags }, null)</th>
            }
        </tr>
    </thead>

    @foreach (var node in Model.Where(_ => !_.Is_Super_Node).OrderBy(_ => _.Description))
    {
        var current_assignment =
            ((IEnumerable<Distance_Analyzer.Models.Node>)ViewBag.SuperNodes)
            .Where(s => node.Tags.Contains((string)s.Description))
            .FirstOrDefault();

        var to_current =
            node
            .Mappings
            .Where(m => m.To == current_assignment?.id)
            .FirstOrDefault();

        <tr>
            <td>
                @if (node.Is_Super_Node)
                {
                    <span class="label label-success">Super Node</span>
                }
                @foreach (var tag in node.Tags)
                {
                    <span class="label">@Html.ActionLink(tag, "Index", "Home", new { Tags = new[] { tag }, ViewBag.supernode }, null)</span>
                }
            </td>
            <td>@Html.ActionLink(node.Description, "Node", new { node.id })</td>
            <td>
                @if (!node.Mappings.Any())
                {
                    @using (Html.BeginForm("Process", "Home", new { node.id }, FormMethod.Post))
                    {
                        <span class="label label-danger"><button type="submit" class="btn-link" formtarget="_blank">Unprocessed</button></span>
                    }
                }
            </td>
            @foreach (var super in ViewBag.SuperNodes)
            {
                var entry = node.Mappings.Where(_ => _.To == super.id).SingleOrDefault();

                @if (super.id == current_assignment?.id)
                {
                    <td class="label-info">
                        @Html.DisplayFor(_ => entry.Driving_Time)
                    </td>
                }
                else
                {
                    var delta = entry?.Driving_Time - to_current?.Driving_Time;

                    <td>
                        @Html.DisplayFor(_ => entry.Driving_Time)
                        <span class="small">(@delta)</span>
                    </td>
                }

            }
        </tr>
    }

    <tfoot>
        <tr>
            <th colspan="3" class="text-center">Avg Drive (min)</th>
            @foreach (var super in ViewBag.SuperNodes)
            {
                var average =
                    Model
                    .SelectMany(_ => _.Mappings)
                    .Where(_ => _.To == super.id)
                    .Select(_ => (Decimal)_.Driving_Time.TotalMinutes)
                    .Average();

                <th>@Math.Round(average, decimals: 2)</th>
            }
        </tr>
    </tfoot>
</table>

@using (Html.BeginForm("Process_All", "Home", new { take = 10 }, FormMethod.Post))
{
    <button type="submit" class="btn btn-danger">Process Next Batch!</button>
}

src/Distance-Analyzer/Views/Home/New.cshtml
@model Distance_Analyzer.Models.Node

<hr />

<h3>Add a New Node for Analsis</h3>

@using (Html.BeginForm("New", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(_ => _.id)
    @Html.HiddenFor(_ => _.Raw)
    @Html.HiddenFor(_ => _.Latitude)
    @Html.HiddenFor(_ => _.Longitude)

    <div class="form-group form-group-xlg">
        @Html.LabelFor(_ => _.Description)
        @Html.EditorFor(_ => _.Description, new { @class = "form-control", required = "required" })
    </div>

    <div class="form-group form-group-xlg">
        @Html.LabelFor(_ => _.Address)
        @Html.TextAreaFor(_ => _.Address, new { @class = "form-control", required = "required" })
    </div>

    <div class="form-group form-group-xlg">
        @Html.LabelFor(_ => _.Is_Super_Node)
        @Html.EditorFor(_ => _.Is_Super_Node, new { @class = "form-control", required = "required" })
    </div>

    <button type="submit">Save</button>
}

src/Distance-Analyzer/Views/Home/Node.cshtml
@model Distance_Analyzer.Models.Node

@using (Html.BeginForm("Process", "Home", new { Model.id }, FormMethod.Post))
{
    <button type="submit">Process This Node</button>
}

@Html.ActionLink("Edit", "Edit", new { Model.id })

<fieldset>
    <legend>@Html.DisplayFor(_ => _.Description)</legend>

    <div>
        @Html.LabelFor(_ => _.Is_Super_Node)
        @Html.DisplayFor(_ => _.Is_Super_Node)
    </div>

    <div>
        @Html.LabelFor(_ => _.Address)
        @Html.DisplayFor(_ => _.Address)
    </div>

    <div>
        <ul>
            @foreach (var tag in Model.Tags)
            {
                <li>@Html.ActionLink(tag, "Index", "Home", new { Tags = new[] { tag } }, null)</li>
            }
        </ul>
    </div>
</fieldset>

<hr />

<h3>Drive Times to Other Nodes</h3>

<table class="table">

    <thead>
        <tr>
            <th>@Html.DisplayNameFor(_ => Model.Mappings.FirstOrDefault().To)</th>
            <th>@Html.DisplayNameFor(_ => Model.Mappings.FirstOrDefault().Distance_Meters)</th>
            <th>@Html.DisplayNameFor(_ => Model.Mappings.FirstOrDefault().Driving_Time)</th>
        </tr>
    </thead>

    @foreach (var mapped in Model.Mappings)
    {
        <tr>
            <td>@await Component.InvokeAsync("Node", new { id = mapped.To })</td>
            <td>@Html.DisplayFor(_ => mapped.Distance_Meters)</td>
            <td>@Html.DisplayFor(_ => mapped.Driving_Time)</td>
        </tr>
    }
</table>

<hr />

@*@await Component.InvokeAsync("Map", new { Model.id })*@

@using (Html.BeginForm("Delete", "Home", new { Model.id }))
{
    <button class="btn-danger">Delete</button>
}

src/Distance-Analyzer/Views/Home/Scrub.cshtml
@model IEnumerable<Distance_Analyzer.Services.MapsService.Result>

<div class="alert alert-info">
    Enter in the raw node address. We will try and geocode it to find a matching address.
</div>

@using (Html.BeginForm("Scrub", "Home", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="form-group form-group-xlg">
        @Html.Label("Raw Address")
        @Html.TextArea("raw_address", new { @class = "form-control" })
    </div>

    <button type="submit">Scrub</button>
}

@if (Model.Any())
{
    <table class="table">
        @foreach (var result in Model)
        {
            <td>@Html.DisplayFor(_ => result)</td>
        }
    </table>
}